DISPATCH-2368: chore(build): add a missing `(void)` into C function declarations
This is an intermediate step (in C23 this can be handled differently), but for now it's the most reasonable fix.

Fixes compilation failures such as this one

```
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
```