DISPATCH-2368: chore(build): add missing `#include <unistd.h>`
Fixes compilation failures such as this one

```
/builddir/build/BUILD/qpid-dispatch-1.19.0/src/dispatch.c:412:26: error: implicit declaration of function ‘getpid’; did you mean ‘getpt’? [-Wimplicit-function-declaration]
  412 |     const pid_t my_pid = getpid();
      |                          ^~~~~~
      |                          getpt
```

from https://bugzilla.redhat.com/show_bug.cgi?id=2245601