DISPATCH-2368: chore(build): add missing `#include <sys/time.h>`
Fixes compilation failures such as this one

```
error: call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```